export const FIREBASE_API_KEY = `${process.env.NEXT_PUBLIC_FIREBASE_API_KEY}`;
export const FIREBASE_AUTH_DOMAIN = `${process.env.NEXT_PUBLIC_FIREBASE_DOMAIN}`;
export const FIREBASE_PROJECT_ID = `${process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID}`;
export const FIREBASE_STORAGE_BUCKET = `${process.env.NEXT_PUBLIC_FIREBASE_BUCKET}`;
export const FIREBASE_MESSAGING_SENDER_ID = `${process.env.NEXT_PUBLIC_FIREBASE_MESSAGE_ID}`;
export const FIREBASE_APP_ID = `${process.env.NEXT_PUBLIC_FIREBASE_APP_ID}`;
